export enum ActionType {
  ADD = 'ADD',
  ADD_SUCCESS = "ADD_SUCCESS",
  ADD_ERROR = "ADD_ERROR",
  EDIT = 'EDIT',
  EDIT_SUCCESS = 'EDIT_SUCCESS',
  EDIT_ERROR = 'EDIT_ERROR',
  DELETE = 'DELETE',
  DELETE_ERROR = 'DELETE_ERROR',
  RETRIEVE = 'RETRIEVE',
  RETRIEVE_SUCCESS = 'RETRIEVE_SUCCESS',
  RETRIEVE_ERROR = 'RETRIEVE_ERROR',
  CLEAR_NOTES = 'CLEAR_NOTES'
}